services:
  api-server:
    build: .
    ports:
      - "8003:8000"
    volumes:
      - ./src:/app/src
    networks:
      - todo-app-example
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - todo-app-example
    volumes:
      - mongo-data:/data/db

networks:
  todo-app-example:
    driver: bridge

volumes:
  mongo-data:
    driver: local